version: "3.8"

services:
  app:
    image: starksim/cas
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./config.yaml:/app/github.com/stark-sim/cas/config.yaml
    container_name: "cas"
    networks:
      default:
        aliases:
          - cas

networks:
  default:
    name: graphql_federation
    external: true
